// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analyzer} from '../models';
import {tokenizer} from '../models';
import {storage} from '../models';

export function AnalyzeProject(arg1:string):Promise<analyzer.DetectionResult>;

export function CheckTokenWarnings(arg1:string):Promise<Array<tokenizer.Warning>>;

export function CountTokens(arg1:string):Promise<number>;

export function ExportToFile(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetProjectByPath(arg1:string):Promise<storage.Project>;

export function GetTemplates():Promise<Array<storage.Template>>;

export function GetTemplatesByStack(arg1:Array<string>):Promise<Array<storage.Template>>;

export function PreviewExport(arg1:number,arg2:string):Promise<string>;

export function SaveTemplate(arg1:storage.Template):Promise<void>;
