// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeProject(arg1) {
  return window['go']['main']['App']['AnalyzeProject'](arg1);
}

export function CheckTokenWarnings(arg1) {
  return window['go']['main']['App']['CheckTokenWarnings'](arg1);
}

export function CountTokens(arg1) {
  return window['go']['main']['App']['CountTokens'](arg1);
}

export function ExportToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToFile'](arg1, arg2, arg3);
}

export function GetProjectByPath(arg1) {
  return window['go']['main']['App']['GetProjectByPath'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetTemplatesByStack(arg1) {
  return window['go']['main']['App']['GetTemplatesByStack'](arg1);
}

export function PreviewExport(arg1, arg2) {
  return window['go']['main']['App']['PreviewExport'](arg1, arg2);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}
